export function safe(v) {
  return String(v || '')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;');
}

export function li(items = []) {
  return items.map((x) => `<li>${safe(x)}</li>`).join('');
}

export function section(title, body) {
  return `
    <section class="sec">
      <h2 class="secTitle">${safe(title)}</h2>
      <div class="secBody">${body}</div>
    </section>
  `;
}

export function watermarkHtml({ watermark, brandName }) {
  if (!watermark) return '';
  const text = `Generated by ${brandName} – Upgrade to remove watermark`;
  return `<div class="watermark">${safe(text)}</div>`;
}

export function safeImgSrc(dataUrl) {
  if (!dataUrl) return '';
  const v = String(dataUrl);
  const ok = /^data:image\/(png|jpe?g|webp);base64,[a-z0-9+/=\s]+$/i.test(v);
  return ok ? v : '';
}

export function avatarHtml(photoDataUrl) {
  const src = safeImgSrc(photoDataUrl);
  if (!src) return '';
  return `
    <div class="avatar">
      <img src="${src}" alt="Profile photo" />
    </div>
  `;
}

export function wrapDocument({ title = 'Resume', css, body }) {
  return `
<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${safe(title)}</title>
    <style>
      :root {
        color-scheme: light;
        --base-font: 12px;
        --title-font: 26px;
        --section-gap: 14px;
        --line-height: 1.45;
      }
      * { box-sizing: border-box; }
      body { font-family: Arial, Helvetica, sans-serif; margin: 0; padding: 0; color: #111; }
      .page { padding: 32px; }
      .watermark {
        position: fixed;
        top: 48%;
        left: 50%;
        transform: translate(-50%, -50%) rotate(-22deg);
        font-size: 28px;
        color: rgba(0,0,0,0.10);
        z-index: 9999;
        pointer-events: none;
        white-space: nowrap;
        text-align: center;
        width: 100%;
      }
      .sec { margin-top: var(--section-gap); }
      .secTitle { font-size: 13px; letter-spacing: 0.08em; text-transform: uppercase; margin: 0 0 6px 0; }
      .secBody { font-size: var(--base-font); line-height: var(--line-height); }
      p { margin: 0 0 8px 0; }
      ul { margin: 6px 0 0 16px; padding: 0; }
      li { margin: 2px 0; }
      .muted { color: #555; }
      .row { display: flex; justify-content: space-between; gap: 16px; }
      .right { white-space: nowrap; }
      .item { margin-top: 8px; }
      .avoidBreak { page-break-inside: avoid; break-inside: avoid; }
      .avatar { width: 64px; height: 64px; border-radius: 14px; overflow: hidden; border: 1px solid #e5e7eb; flex: none; }
      .avatar img { width: 100%; height: 100%; object-fit: cover; }

      ${css || ''}
    </style>
  </head>
  <body>
    ${body}
  </body>
</html>
`;
}
